### ISSUE TITLE
Maybe an misleading WARNING

### ISSUE THREAD

**Issue by zekunzhao** [rayleizhu/vllm-ra#5]
Hi, @rayleizhu 

I used the function in my Python script to cache the system_prompt  with enable_relay_attention, which is set as true.
`llm.fill_prefix_kv_cache(system_prompt)`.

But I get this warning in the generation:

> WARNING 12-09 19:45:12 llm_engine.py:271] Though enable_relay_attention is set as true, relay attention is not activated due to no system prompt is provided.

Is this warning not correct?  I assume that the relay attention is activated in this case.

**Comment by rayleizhu** [comment]
This warning emerges when the system kv cache is not filled when the service is instantiated. But indeed you can fill or overwrite the KV cache after the instantiation.

On 9 Dec 2024, at 1:33 PM, zekun ***@***.***> wrote:



Hi, @rayleizhu<https://github.com/rayleizhu>

I used the function to cache the system_prompt with enable_relay_attention is set as true.
llm.fill_prefix_kv_cache(system_prompt).

But I get this warning in the generation:

WARNING 12-09 19:45:12 llm_engine.py:271] Though enable_relay_attention is set as true, relay attention is not activated due to no system prompt is provided.

Is this warning not correct? I assume that the relay attention is activated in this case.
